In [1]:
import numpy as np

### create an array from an iterable

In [2]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### create an array in a specified data type

In [4]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


### create an aray of evenly spaced values within a specified interval

In [5]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


### create an array of evenly spaced numbers in a specified interval

In [6]:
# np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) 
arr = np.linspace(0, 5, 8)
print(arr)

[0.         0.71428571 1.42857143 2.14285714 2.85714286 3.57142857
 4.28571429 5.        ]


In [7]:
# exclude endpoint and return setp size
arr, step = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print(step)

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
0.625


### create an array of random values in a given shape

In [8]:
arr = np.random.rand(3, 3)
print(arr)

[[0.11785484 0.44650756 0.93152485]
 [0.48604524 0.26244565 0.23107835]
 [0.97102094 0.52276269 0.57212381]]


### create an array of zeros in a given shape 

In [9]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


### create an array of zeros with the same shape and data type as a given array

In [10]:
zeros = np.zeros_like(arr)
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### create an array of ones in a given shape 

In [11]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


### create an array of ones with the same shape and data type as a given array

In [12]:
ones = np.ones_like(arr)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### create an array of arbitrary values in a given shape 

In [13]:
empty = np.empty((2,3))
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]]


### create an array of arbitrary values with the same shape and data type as a given array

In [14]:
empty = np.empty_like(arr)
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### create an array of constant values in a given shape  

In [15]:
p = np.full((2,3), 5)
print(p)

[[5 5 5]
 [5 5 5]]


### create an array of constant values with the same shape and data type as a given array

In [16]:
p = np.full_like(arr, 5)
print(p)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


### create an array by repetition

In [17]:
# repeat each element of an array by a specified number of times
# np.repeat(iterable, reps, axis=None)
arr = [0, 1, 2]
print(np.repeat(arr, 3))    # or np.repeat(range(3), 3)

[0 0 0 1 1 1 2 2 2]


In [18]:
# repeat along a specified axis with specified number of repetitions
arr = [[1,2], [3,4]]
print(np.repeat(arr, [1,2], axis=0))

[[1 2]
 [3 4]
 [3 4]]


In [19]:
# repeat an array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [20]:
# repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


### create an identity matrix with a given diagonal size

In [21]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### create an identity matrix with a diagonal offset

In [23]:
identity_matrix = np.eye(5, k=1)    # positive number shifts the diagonal upward
print(identity_matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [24]:
identity_matrix = np.eye(5, k=-2)   # negative number shifts the diagonal downward
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### extract the diagonal array / create a diagonal array

In [25]:
arr = np.random.rand(5,5)
print(arr)

[[0.99931921 0.64356337 0.45724831 0.61617641 0.23871372]
 [0.88593381 0.32146327 0.27611971 0.67752217 0.53161681]
 [0.13434934 0.10498863 0.65124796 0.3256571  0.59753227]
 [0.96755184 0.60432796 0.09791616 0.86357947 0.50917921]
 [0.29174581 0.16261553 0.28466243 0.51570616 0.57387334]]


In [26]:
# extract the diagonal
print(np.diag(arr))

[0.99931921 0.32146327 0.65124796 0.86357947 0.57387334]


In [27]:
# create a matrix with a specified diagonal array
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
