In [1]:
import numpy as np

In [2]:
print('Numpy version: ' + np.__version__)

Numpy version: 1.15.0


## Create Arrays

In [3]:
# create an array with iterable or an Python array
arr = np.array(range(10))
print(arr)
arr = np.array([1,2,3,4,5])
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


In [4]:
# create an aray with np.arange(start, end, step)
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [5]:
# create an array with np.linspace(start, end, num, endpoint=True, retstep=False)
# exclude the endpoint and return step size
arr = np.linspace(0, 10, 20, endpoint=False, retstep=True)

In [6]:
# create a random array
arr = np.random.random((3,3))
print(arr)

[[0.85868662 0.0798     0.24213507]
 [0.147229   0.87583339 0.05820904]
 [0.48101135 0.54427612 0.40494308]]


In [7]:
# specify data type when creating an array
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
# create an array of zeros 
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
zeros = np.zeros_like(arr)
print(zeros)

[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]


In [9]:
# create an array of ones
ones = np.ones((2,3), dtype=np.int32)
print(ones)
ones = np.ones_like(arr, dtype=np.int16)
print(ones)

[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]


In [10]:
# create an array of arbitrary values
empty = np.empty((2,3))
print(empty)
empty = np.empty_like(arr)
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]]
[[8224 8224 8224]
 [8224 8224 8289]]


In [11]:
# create an array of pre-filled values 
p = np.full((2,3), 5, dtype=np.int32)
print(p)
p = np.full_like(arr, 5)
print(p)

[[5 5 5]
 [5 5 5]]
[[5 5 5]
 [5 5 5]]


In [12]:
# create an identity matrix 
identity_matrix = np.eye(5)
print(identity_matrix)
# or 
identity_matrix = np.identity(5)
print(identity_matrix)
# diagonal offset
identity_matrix = np.eye(5, k=1)
print(identity_matrix)
identity_matrix = np.eye(5, k=-2)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Inspect Arrays

In [13]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

In [14]:
# inspect general information of an array
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1ec322efc60
byteorder:  little
byteswap:  False
type: int64
None


In [15]:
# the data type of the array
print(arr.dtype)

int64


In [16]:
# the dimension of the array
print(arr.shape)

(2, 3)


In [17]:
# length of the array
print(len(arr))

2


In [18]:
# number of the dimension of the array
print(arr.ndim)

2


In [19]:
# number of elements in the array
print(arr.size)

6


In [20]:
# number of bytes of each element in the array
print(arr.itemsize)

8


## Data Types

In [21]:
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

In [22]:
arr = np.array([1,2,3,4,5], dtype=np.int32)
print(arr.dtype)

int32


In [23]:
# convert data type
arr1 = arr.astype('i8')  
print(arr1.dtype)

arr2 = arr.astype(np.float32)
print(arr2.dtype)

int64
float32


In [24]:
# set the length of string using S + length, for example 'S10' means a string of length 10
s = np.array(['abc', 'defg'], dtype='S10')

# the default data type np.string_ will set the length to be the longest length of all elements
s = np.array([1.96,2.0,8], dtype=np.string_)
print(s.dtype)

|S4


## Sampling Methods

In [25]:
# set seed
np.random.seed(123)

In [26]:
# generate random values from interval [0, 1) in a given shape
print(np.random.rand())             # generate a single random value
print(np.random.rand(3,))           # generate a 1-D array
print(np.random.rand(3,3))          # generate a 2-D array

0.6964691855978616
[0.28613933 0.22685145 0.55131477]
[[0.71946897 0.42310646 0.9807642 ]
 [0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]]


In [27]:
# generate radom values from standard normal distribution (mean:o, variance:1)
print(np.random.randn(3,3))

[[-0.14337247 -0.6191909  -0.76943347]
 [ 0.57674602  0.12652592 -1.30148897]
 [ 2.20742744  0.52274247  0.46564476]]


In [28]:
# generate a random array of integers in interval [low, high)
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1,10,3,'i8'))

[5 7 2]


In [29]:
# generate a random array of floats in the interval [0.0, 1.0)
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.65472131 0.37380143 0.23451288 0.98799529 0.76599595 0.77700444
 0.02798196 0.17390652 0.15408224 0.07708648]
[0.8898657  0.7503787  0.69340324 0.51176338 0.46426806 0.56843069
 0.30254945 0.49730879 0.68326291 0.91669867]
[0.10892895 0.49549179 0.23283593 0.43686066 0.75154299 0.48089213
 0.79772841 0.28270293 0.43341824 0.00975735]
[0.34079598 0.68927201 0.86936929 0.26780382 0.45674792 0.26828131
 0.8370528  0.27051466 0.53006201 0.17537266]


In [30]:
# generate a random sample from a given 1-D array
# np.random.choice(array-like_or_int, size, replace=True, p)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))
print(np.random.choice(3, 10))
print(np.random.choice([1,2,3], 10))

[1 1 1 1 1 1 1 2 2 1]
[1 0 1 2 2 0 1 1 1 0]
[2 2 1 3 2 3 1 2 1 3]


In [31]:
# shuffle an array in place
arr = np.array(range(10))
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 2 8 5 4 0 6 7 9 3]


In [32]:
# return a permutation of an array
arr = np.array(range(10))
print(arr)
print(np.random.permutation(arr))

[0 1 2 3 4 5 6 7 8 9]
[3 6 2 4 5 9 1 8 0 7]


## Mathematical Functions

In [33]:
arr = np.random.rand(5,5)

In [34]:
# element-wise mathematical operations
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.87350227 10.02942373 10.55204372 10.2402475  10.88480501]
 [10.46023842 10.19317033 10.2936925  10.81792751 10.55948738]
 [10.67792545 10.80912668 10.86857215 10.41799246 10.05893816]
 [10.478459   10.52115943 10.58063202 10.309199   10.91988263]
 [10.6553475  10.34924138 10.54109404 10.4490534  10.28232096]]
[[-9.12649773 -9.97057627 -9.44795628 -9.7597525  -9.11519499]
 [-9.53976158 -9.80682967 -9.7063075  -9.18207249 -9.44051262]
 [-9.32207455 -9.19087332 -9.13142785 -9.58200754 -9.94106184]
 [-9.521541   -9.47884057 -9.41936798 -9.690801   -9.08011737]
 [-9.3446525  -9.65075862 -9.45890596 -9.5509466  -9.71767904]]
[[8.73502266 0.29423734 5.52043722 2.40247504 8.84805011]
 [4.60238424 1.9317033  2.93692504 8.17927508 5.59487376]
 [6.77925447 8.09126678 8.68572154 4.17992456 0.58938156]
 [4.78459005 5.2115943  5.8063202  3.09198998 9.19882625]
 [6.55347503 3.49241385 5.41094045 4.49053396 2.82320961]]
[[0.08735023 0.00294237 0.05520437 0.02402475 0.0884805 ]
 [0.04602384 0.0193

In [35]:
# exponentiation
print(np.exp(arr))

[[2.39528511 1.02986089 1.73679893 1.27156383 2.42251198]
 [1.58445171 1.2130894  1.34137137 2.26579912 1.74977529]
 [1.96978706 2.2459457  2.38350515 1.51890922 1.06070964]
 [1.61358596 1.68397897 1.7871676  1.36233345 2.50899588]
 [1.92581163 1.41799143 1.71788528 1.56682832 1.32620431]]


In [36]:
# logorithm
print(np.log(arr))      # natural log
print(np.log2(arr))     # base 2
print(np.log10(arr))    # base 10

[[-0.13524456 -3.52595367 -0.59412803 -1.42608562 -0.12238798]
 [-0.77601061 -1.64418294 -1.22522197 -0.20098157 -0.58073432]
 [-0.38871796 -0.21179979 -0.14090462 -0.87229189 -2.83126659]
 [-0.73718475 -0.65169928 -0.54363808 -1.1737702  -0.0835092 ]
 [-0.42258965 -1.05199195 -0.61416218 -0.80061348 -1.2647107 ]]
[[-0.19511665 -5.08687587 -0.85714556 -2.05740665 -0.17656854]
 [-1.11954666 -2.37205457 -1.76762165 -0.28995511 -0.83782252]
 [-0.56080147 -0.3055625  -0.20328239 -1.25845119 -4.08465428]
 [-1.06353278 -0.94020332 -0.78430396 -1.69339245 -0.12047831]
 [-0.60966799 -1.51770357 -0.88604873 -1.15504109 -1.82459185]]
[[-0.05873596 -1.53130222 -0.25802652 -0.61934112 -0.05315243]
 [-0.33701713 -0.71405958 -0.53210714 -0.08728519 -0.25220971]
 [-0.16881806 -0.09198348 -0.0611941  -0.37883156 -1.22960346]
 [-0.32015527 -0.2830294  -0.23609902 -0.50976192 -0.03626758]
 [-0.18352835 -0.4568743  -0.26672725 -0.34770202 -0.54925688]]


In [37]:
# square root
print(np.sqrt(arr))

[[0.93461343 0.17153348 0.74299645 0.49015049 0.94064075]
 [0.67840874 0.43951147 0.54193404 0.90439345 0.74798889]
 [0.82336228 0.89951469 0.93197219 0.64652336 0.24277182]
 [0.69170731 0.72191373 0.76199214 0.55605665 0.95910512]
 [0.80953536 0.59096648 0.73559095 0.67011446 0.53133884]]


In [38]:
# sine and cosine
print(np.sin(arr))
print(np.cos(arr))

[[0.7665826  0.02941949 0.52442846 0.23794303 0.77379149]
 [0.44416174 0.19197122 0.28948859 0.72973036 0.5307518 ]
 [0.62717856 0.72368474 0.76340745 0.40592657 0.05890404]
 [0.46041177 0.49788598 0.54855249 0.30429572 0.79553051]
 [0.60943479 0.34218509 0.51507406 0.43411297 0.27858547]]
[[0.64214571 0.99956715 0.85145452 0.97127911 0.63344039]
 [0.89594662 0.98140056 0.95718147 0.68373503 0.8475273 ]
 [0.77887551 0.69013071 0.64591723 0.9139057  0.99826365]
 [0.88770547 0.8672425  0.83611612 0.95257762 0.60591354]
 [0.7928362  0.93963257 0.85714568 0.90085844 0.96041144]]


In [39]:
# matrix multiplication
print(arr.dot(arr))
# or
print(arr @ arr)

[[1.84559596 0.91227657 1.58860089 0.93628231 1.29267633]
 [1.44802877 0.91015793 1.34354773 0.89547378 1.44295964]
 [1.792005   1.11745562 1.6408874  1.3434427  1.50486351]
 [1.80219967 1.0669585  1.59878556 1.29259946 1.29327536]
 [1.49987523 0.85718605 1.34782624 0.93489701 1.29992353]]
[[1.84559596 0.91227657 1.58860089 0.93628231 1.29267633]
 [1.44802877 0.91015793 1.34354773 0.89547378 1.44295964]
 [1.792005   1.11745562 1.6408874  1.3434427  1.50486351]
 [1.80219967 1.0669585  1.59878556 1.29259946 1.29327536]
 [1.49987523 0.85718605 1.34782624 0.93489701 1.29992353]]


In [40]:
# sum 
print(np.sum(arr, axis=0))    # sum along the row
print(np.sum(arr, axis=1))    # sum along the column

[3.14547265 1.90212156 2.83603444 2.23441986 2.70543413]
[2.58002224 2.32451614 2.83255489 2.80933208 2.27705729]


In [41]:
# min and max
print(np.min(arr, axis=0))    # calculate min along the row
print(np.max(arr, axis=1))    # calculate max along the column

[0.46023842 0.02942373 0.2936925  0.2402475  0.05893816]
[0.88480501 0.81792751 0.86857215 0.91988263 0.6553475 ]


In [42]:
# element-wise min and max of two arrays
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


In [43]:
# get fractional and integral parts of a floating-point array
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print(re)
print(intg)

[0.95876525 0.63480983 0.15191279 0.17618677 0.52041829 0.32778859
 0.7311902  0.67888445 0.87478322 0.4941493 ]
[2. 5. 7. 5. 3. 6. 8. 1. 9. 3.]


In [44]:
# mean and median
print(np.mean(arr, axis=0))   # calculate the mean along the row
print(np.mean(arr, axis=1))   # calculate the mean along the column
print(np.median(arr, axis=0)) # calculate the median along the row
print(np.median(arr, axis=1)) # calculate the median along the column

[0.62909453 0.38042431 0.56720689 0.44688397 0.54108683]
[0.51600445 0.46490323 0.56651098 0.56186642 0.45541146]
[0.6553475  0.34924138 0.55204372 0.41799246 0.55948738]
[0.55204372 0.46023842 0.67792545 0.52115943 0.4490534 ]


In [45]:
# standard deviation and variance
print(np.std(arr))
print(np.var(arr))

0.25305273176784365
0.06403568505516823


In [46]:
# cumulative sum and product
print(np.cumsum(arr, axis=1))    # calculate the cumulative sums along the column
print(np.cumprod(arr, axis=1))   # calculate the cumulative product along the column

[[0.87350227 0.902926   1.45496972 1.69521723 2.58002224]
 [0.46023842 0.65340875 0.94710126 1.76502877 2.32451614]
 [0.67792545 1.48705213 2.35562428 2.77361674 2.83255489]
 [0.478459   0.99961843 1.58025045 1.88944945 2.80933208]
 [0.6553475  1.00458889 1.54568293 1.99473633 2.27705729]]
[[0.87350227 0.0257017  0.01418846 0.00340874 0.00301607]
 [0.46023842 0.08890441 0.02611056 0.02135654 0.01194872]
 [0.67792545 0.54852757 0.47643577 0.19914656 0.01173733]
 [0.478459   0.24935342 0.14478258 0.04476663 0.04118004]
 [0.6553475  0.22887447 0.12384261 0.05561195 0.01570042]]


In [47]:
# comparison 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])
print(arr1 == arr2)    # return an array of bools
print(arr1 < 3)        # return an array of bools

[False False  True False False]
[ True  True False False False]


## Slicing & Indexing

In [48]:
arr = np.array(range(100)).reshape((10,10))

In [49]:
# select an element by row and column indices
print(arr[5][5])
# or 
print(arr[5,5])

55
55


In [50]:
# indexing with slicing
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [51]:
# assign a scalar to a slice by broadcasting
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[  0   1   2   3   4   5   6   7 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37 100 100]
 [ 40  41  42  43  44  45  46  47 100 100]
 [ 50  51  52  53  54  55  56  57 100 100]
 [ 60  61  62  63  64  65  66  67 100 100]
 [ 70  71  72  73  74  75  76  77 100 100]
 [ 80  81  82  83  84  85  86  87 100 100]
 [ 90  91  92  93  94  95  96  97 100 100]]


In [52]:
# boolean indexing
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])
print(arr1[~bools])    # negate the condition

arr2 = np.array([1,2,3,4,5])
print(arr1[(arr2<2) | (arr2>4)])    # multiple conditions

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]
[[10 11 12 13 14]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [20 21 22 23 24]]


In [53]:
# fancy indexing
print(arr[[3,1,2], [3,2,1]])       # select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2]][:, [6,4,8]])    # select rows 3,1,2 and columns 6,4,8 

[ 33 100 100]
[[ 36  34 100]
 [100 100 100]
 [100 100 100]]


In [54]:
# ellipsis slicing
arr = np.array(range(16)).reshape(2,2,2,2)
print(arr[0,...])    # equivalent to arr[0,:,:,:]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [55]:
# dimension inference using -1
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


## Sort Arrays

In [56]:
arr = np.random.rand(5,5)
# return a sorted array
print(np.sort(arr, axis=0))    # sort along the row
print(np.sort(arr, axis=1))    # sort along the column

# sort in place
arr.sort(axis=0)    # sort along the row
print(arr)
arr.sort(axis=1)    # sort along the column
print(arr)

[[0.06756083 0.02755138 0.00535329 0.24182762 0.05608301]
 [0.19940777 0.06546154 0.48817449 0.41679514 0.25584293]
 [0.38151211 0.19017372 0.50942926 0.50236965 0.40335482]
 [0.40518518 0.47387186 0.81103914 0.68618686 0.91131813]
 [0.82620513 0.80738444 0.81733492 0.88694465 0.99261363]]
[[0.00535329 0.06546154 0.82620513 0.88694465 0.91131813]
 [0.02755138 0.05608301 0.19940777 0.24182762 0.81733492]
 [0.06756083 0.25584293 0.41679514 0.47387186 0.50942926]
 [0.38151211 0.68618686 0.80738444 0.81103914 0.99261363]
 [0.19017372 0.40335482 0.40518518 0.48817449 0.50236965]]
[[0.06756083 0.02755138 0.00535329 0.24182762 0.05608301]
 [0.19940777 0.06546154 0.48817449 0.41679514 0.25584293]
 [0.38151211 0.19017372 0.50942926 0.50236965 0.40335482]
 [0.40518518 0.47387186 0.81103914 0.68618686 0.91131813]
 [0.82620513 0.80738444 0.81733492 0.88694465 0.99261363]]
[[0.00535329 0.02755138 0.05608301 0.06756083 0.24182762]
 [0.06546154 0.19940777 0.25584293 0.41679514 0.48817449]
 [0.1901737

## Copy Arrays

In [57]:
# deep copy 
arr = np.array([1,2,3])
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

## Manipulate Arrays

In [58]:
arr = np.random.rand(3,4)

In [59]:
# transpose an array
print(arr.T)
# or 
print(np.transpose(arr))
print(arr.transpose())

# transpose of a high dimensional array
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)
arr1.transpose((1,0,2))
print(arr1)

# swap axes
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[0.18109542 0.881347   0.05662   ]
 [0.0480298  0.58404612 0.15703523]
 [0.60469135 0.47746048 0.3386175 ]
 [0.26591121 0.17151502 0.44064297]]
[[0.18109542 0.881347   0.05662   ]
 [0.0480298  0.58404612 0.15703523]
 [0.60469135 0.47746048 0.3386175 ]
 [0.26591121 0.17151502 0.44064297]]
[[0.18109542 0.881347   0.05662   ]
 [0.0480298  0.58404612 0.15703523]
 [0.60469135 0.47746048 0.3386175 ]
 [0.26591121 0.17151502 0.44064297]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [60]:
# change the shape of an array
arr.reshape((2,6))
# change the shape of an array in place
arr.resize((2,6))
# flatten an array
arr.flatten()    # return a copy
arr.ravel()      # return a view

array([0.18109542, 0.0480298 , 0.60469135, 0.26591121, 0.881347  ,
       0.58404612, 0.47746048, 0.17151502, 0.05662   , 0.15703523,
       0.3386175 , 0.44064297])

In [61]:
# append, insert and delete elements
# the following operations return a copy instead of making changes in place
arr = np.array([1,2,3])
arr1 = np.append(arr, 4)    # append a number
print(arr1)

arr2 = np.append(arr, [4,5,6])    # append an array
print(arr2)

# np.insert(array, position, element)
arr3 = np.insert(arr, 0, 100)    # insert a single element at a certain position
print(arr3)

arr3 = np.insert(arr, 0, [1,2,3])    # insert multiple elements at a certain position
print(arr3)

arr4 = np.delete(arr, 0)    # remove the element at position 0
print(arr4)

arr4 = np.delete(arr, [0,2])    # remove the element at multiple positions
print(arr4)

[1 2 3 4]
[1 2 3 4 5 6]
[100   1   2   3]
[1 2 3 1 2 3]
[2 3]
[2]


## Combine & Split Arrays

In [62]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [63]:
# np.concatenate((a,b), axis=0)
cat = np.concatenate((arr1, arr2), axis=0)    # concat along the row    
print(cat)

cat = np.concatenate((arr1, arr2), axis=1)    # concat along the column
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [64]:
# np.vstack((a,b)): stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)
# or 
cat = np.r_[arr1, arr2]
print(cat)

# np.hstack((a,b)): stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)
# or 
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [65]:
arr = np.random.rand(6,6)

# split the array vertically at a certain index
arr1 = np.vsplit(arr, 2)
print(arr1)

# split the array horizontally at a certain index
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.68384312, 0.20587172, 0.6164337 , 0.92447161, 0.07962825,
        0.48539683],
       [0.69856363, 0.08156848, 0.86910236, 0.43310568, 0.49433006,
        0.49574047],
       [0.37072208, 0.92212866, 0.84127822, 0.65552592, 0.46268505,
        0.56501131]]), array([[0.42391551, 0.28821195, 0.26398072, 0.69073823, 0.83283653,
        0.59239158],
       [0.46652258, 0.67365999, 0.39147935, 0.70210437, 0.96569764,
        0.09050988],
       [0.05812514, 0.58801742, 0.75117376, 0.51131739, 0.92050119,
        0.3039641 ]])]
[array([[0.68384312, 0.20587172, 0.6164337 ],
       [0.69856363, 0.08156848, 0.86910236],
       [0.37072208, 0.92212866, 0.84127822],
       [0.42391551, 0.28821195, 0.26398072],
       [0.46652258, 0.67365999, 0.39147935],
       [0.05812514, 0.58801742, 0.75117376]]), array([[0.92447161, 0.07962825, 0.48539683],
       [0.43310568, 0.49433006, 0.49574047],
       [0.65552592, 0.46268505, 0.56501131],
       [0.69073823, 0.83283653, 0.59239158],
       [