### import numpy

In [1]:
import numpy as np

### check python and numpy version

In [2]:
import platform
print('Python version: ' + platform.python_version())
print('Numpy version: ' + np.__version__)

Python version: 3.6.6
Numpy version: 1.15.0


# 1. Create Arrays

### create an array from an iterable

In [3]:
arr = np.array(range(10))
print(arr)

arr = np.array([1,2,3,4,5])
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


### create an array in a specified data type

In [4]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


### create an aray of evenly spaced values within a specified interval

In [5]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


### create an array of evenly spaced numbers in a specified interval

In [6]:
# np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) 
arr = np.linspace(0, 10, 20)
print(arr)

# exclude endpoint and return setp size
arr, step = np.linspace(0, 10, 20, endpoint=False, retstep=True)
print(arr)
print(step)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
0.5


### create an array of random values in a given shape

In [7]:
arr = np.random.rand(3, 3)
print(arr)

[[0.84881431 0.37832516 0.07001883]
 [0.4702529  0.9827513  0.11391501]
 [0.88884503 0.64346205 0.90634203]]


### create an array of zeros in a given shape 

In [8]:
zeros = np.zeros((2,3), dtype='i4')
print(zeros)

[[0 0 0]
 [0 0 0]]


### create an array of zeros with the same shape and data type as a given array

In [9]:
zeros = np.zeros_like(arr)
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### create an array of ones in a given shape 

In [10]:
ones = np.ones((2,3), dtype=np.int32)
print(ones)

[[1 1 1]
 [1 1 1]]


### create an array of ones with the same shape and data type as a given array

In [11]:
ones = np.ones_like(arr, dtype=np.int16)
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### create an array of arbitrary values in a given shape 

In [12]:
empty = np.empty((2,3))
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]]


### create an array of arbitrary values with the same shape and data type as a given array

In [13]:
empty = np.empty_like(arr)
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### create an array of constant values in a given shape  

In [14]:
p = np.full((2,3), 5, dtype=np.int32)
print(p)

[[5 5 5]
 [5 5 5]]


### create an array of constant values with the same shape and data type as a given array

In [15]:
p = np.full_like(arr, 5)
print(p)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


### create an identity matrix with a given diagonal size

In [16]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### create an identity matrix with a diagonal offset

In [18]:
identity_matrix = np.eye(5, k=1)    # positive number means upper offset by the number
print(identity_matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [19]:
identity_matrix = np.eye(5, k=-2)   # negative number means lower offset by the number
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# 2. Inspect Arrays

In [20]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

### inspect general information of an array

In [21]:
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1f40cf26b90
byteorder:  little
byteswap:  False
type: int64
None


### inspect the data type of an array

In [22]:
print(arr.dtype)

int64


### inspect the dimension of an array

In [23]:
print(arr.shape)

(2, 3)


### inspect length of an array

In [24]:
print(len(arr))

2


### inspect the number of dimensions of an array

In [25]:
print(arr.ndim)

2


### inspect the number of elements in an array

In [26]:
print(arr.size)

6


### inspect the number of bytes of each element in an array

In [27]:
print(arr.itemsize)

8


# 3. Numpy Data Types

### A list of Numpy Data Types

In [28]:
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

### convert data type

In [29]:
arr1 = arr.astype('i8')  
print(arr1.dtype)

int64


In [30]:
arr2 = arr.astype(np.float32)
print(arr2.dtype)

float32


### string data type

In [31]:
# set the max length of the string using S + length, such as 'S10'
# any string longer than the max length will be truncated
s = np.array(['abc', 'defg'], dtype='S10')

In [32]:
# 'np.string_' will set the length of the longest string in the array as the max length 
s = np.array([1.96,2.0,8], dtype=np.string_)
print(s.dtype)

|S4


# 4. Sampling Methods

### set seed

In [33]:
np.random.seed(123)

### set random state which is separate from the global seed

In [34]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [35]:
# generate a random scalar
print(np.random.rand())      

0.6964691855978616


In [36]:
# generate a 1-D array
print(np.random.rand(3,))           

[0.28613933 0.22685145 0.55131477]


In [37]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.71946897 0.42310646 0.9807642 ]
 [0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]]


### generate a sample from the standard normal distribution (with mean equal to o and variance 1)

In [38]:
print(np.random.randn(3,3))

[[-0.14337247 -0.6191909  -0.76943347]
 [ 0.57674602  0.12652592 -1.30148897]
 [ 2.20742744  0.52274247  0.46564476]]


### generate an array of random integers in a given interval [low, high)

In [39]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[5 7 2]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [40]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.65472131 0.37380143 0.23451288 0.98799529 0.76599595 0.77700444
 0.02798196 0.17390652 0.15408224 0.07708648]
[0.8898657  0.7503787  0.69340324 0.51176338 0.46426806 0.56843069
 0.30254945 0.49730879 0.68326291 0.91669867]
[0.10892895 0.49549179 0.23283593 0.43686066 0.75154299 0.48089213
 0.79772841 0.28270293 0.43341824 0.00975735]
[0.34079598 0.68927201 0.86936929 0.26780382 0.45674792 0.26828131
 0.8370528  0.27051466 0.53006201 0.17537266]


### # generate a random sample in a given 1-D array

In [41]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[1 1 1 1 1 1 1 2 2 1]


In [42]:
print(np.random.choice(3, 10))

[1 0 1 2 2 0 1 1 1 0]


In [43]:
print(np.random.choice([1,2,3], 10))

[2 2 1 3 2 3 1 2 1 3]


### shuffle the array in place

In [44]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
np.random.shuffle(arr)
print(arr)

[1 2 8 5 4 0 6 7 9 3]


### generate a permutation of an array

In [46]:
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [3 6 2 4 5 9 1 8 0 7]


# 5. Mathematical Functions

In [47]:
arr = np.random.rand(5,5)

### element-wise addition, subtraction, multiplication and division

In [48]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.87350227 10.02942373 10.55204372 10.2402475  10.88480501]
 [10.46023842 10.19317033 10.2936925  10.81792751 10.55948738]
 [10.67792545 10.80912668 10.86857215 10.41799246 10.05893816]
 [10.478459   10.52115943 10.58063202 10.309199   10.91988263]
 [10.6553475  10.34924138 10.54109404 10.4490534  10.28232096]]
[[-9.12649773 -9.97057627 -9.44795628 -9.7597525  -9.11519499]
 [-9.53976158 -9.80682967 -9.7063075  -9.18207249 -9.44051262]
 [-9.32207455 -9.19087332 -9.13142785 -9.58200754 -9.94106184]
 [-9.521541   -9.47884057 -9.41936798 -9.690801   -9.08011737]
 [-9.3446525  -9.65075862 -9.45890596 -9.5509466  -9.71767904]]
[[8.73502266 0.29423734 5.52043722 2.40247504 8.84805011]
 [4.60238424 1.9317033  2.93692504 8.17927508 5.59487376]
 [6.77925447 8.09126678 8.68572154 4.17992456 0.58938156]
 [4.78459005 5.2115943  5.8063202  3.09198998 9.19882625]
 [6.55347503 3.49241385 5.41094045 4.49053396 2.82320961]]
[[0.08735023 0.00294237 0.05520437 0.02402475 0.0884805 ]
 [0.04602384 0.0193

### element-wise exponentiation

In [49]:
print(np.exp(arr))

[[2.39528511 1.02986089 1.73679893 1.27156383 2.42251198]
 [1.58445171 1.2130894  1.34137137 2.26579912 1.74977529]
 [1.96978706 2.2459457  2.38350515 1.51890922 1.06070964]
 [1.61358596 1.68397897 1.7871676  1.36233345 2.50899588]
 [1.92581163 1.41799143 1.71788528 1.56682832 1.32620431]]


### element-wise logorithm

In [50]:
# natural log
print(np.log(arr))      

[[-0.13524456 -3.52595367 -0.59412803 -1.42608562 -0.12238798]
 [-0.77601061 -1.64418294 -1.22522197 -0.20098157 -0.58073432]
 [-0.38871796 -0.21179979 -0.14090462 -0.87229189 -2.83126659]
 [-0.73718475 -0.65169928 -0.54363808 -1.1737702  -0.0835092 ]
 [-0.42258965 -1.05199195 -0.61416218 -0.80061348 -1.2647107 ]]


In [51]:
# base 2
print(np.log2(arr))     

[[-0.19511665 -5.08687587 -0.85714556 -2.05740665 -0.17656854]
 [-1.11954666 -2.37205457 -1.76762165 -0.28995511 -0.83782252]
 [-0.56080147 -0.3055625  -0.20328239 -1.25845119 -4.08465428]
 [-1.06353278 -0.94020332 -0.78430396 -1.69339245 -0.12047831]
 [-0.60966799 -1.51770357 -0.88604873 -1.15504109 -1.82459185]]


In [52]:
# base 10
print(np.log10(arr))    

[[-0.05873596 -1.53130222 -0.25802652 -0.61934112 -0.05315243]
 [-0.33701713 -0.71405958 -0.53210714 -0.08728519 -0.25220971]
 [-0.16881806 -0.09198348 -0.0611941  -0.37883156 -1.22960346]
 [-0.32015527 -0.2830294  -0.23609902 -0.50976192 -0.03626758]
 [-0.18352835 -0.4568743  -0.26672725 -0.34770202 -0.54925688]]


### element-wise square root

In [53]:
print(np.sqrt(arr))

[[0.93461343 0.17153348 0.74299645 0.49015049 0.94064075]
 [0.67840874 0.43951147 0.54193404 0.90439345 0.74798889]
 [0.82336228 0.89951469 0.93197219 0.64652336 0.24277182]
 [0.69170731 0.72191373 0.76199214 0.55605665 0.95910512]
 [0.80953536 0.59096648 0.73559095 0.67011446 0.53133884]]


### element-wise sine and cosine

In [54]:
print(np.sin(arr))
print(np.cos(arr))

[[0.7665826  0.02941949 0.52442846 0.23794303 0.77379149]
 [0.44416174 0.19197122 0.28948859 0.72973036 0.5307518 ]
 [0.62717856 0.72368474 0.76340745 0.40592657 0.05890404]
 [0.46041177 0.49788598 0.54855249 0.30429572 0.79553051]
 [0.60943479 0.34218509 0.51507406 0.43411297 0.27858547]]
[[0.64214571 0.99956715 0.85145452 0.97127911 0.63344039]
 [0.89594662 0.98140056 0.95718147 0.68373503 0.8475273 ]
 [0.77887551 0.69013071 0.64591723 0.9139057  0.99826365]
 [0.88770547 0.8672425  0.83611612 0.95257762 0.60591354]
 [0.7928362  0.93963257 0.85714568 0.90085844 0.96041144]]


### sum along a specified axis

In [55]:
# sum along the row
print(np.sum(arr, axis=0))    

[3.14547265 1.90212156 2.83603444 2.23441986 2.70543413]


In [56]:
# sum along the column
print(np.sum(arr, axis=1))    

[2.58002224 2.32451614 2.83255489 2.80933208 2.27705729]


### compute the min and max along a specified axis

In [57]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.46023842 0.02942373 0.2936925  0.2402475  0.05893816]


In [58]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.88480501 0.81792751 0.86857215 0.91988263 0.6553475 ]


### compute element-wise min and max of two arrays

In [59]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [60]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.95876525 0.63480983 0.15191279 0.17618677 0.52041829 0.32778859
 0.7311902  0.67888445 0.87478322 0.4941493 ]
integral:  [2. 5. 7. 5. 3. 6. 8. 1. 9. 3.]


### compute the mean

In [61]:
# compute the overall mean
print(np.mean(arr))

0.5129393054604379


In [62]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.62909453 0.38042431 0.56720689 0.44688397 0.54108683]


In [63]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.51600445 0.46490323 0.56651098 0.56186642 0.45541146]


### compute the median

In [64]:
# compute the overall median
print(np.median(arr))

0.52115942968839


In [65]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.6553475  0.34924138 0.55204372 0.41799246 0.55948738]


In [66]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.55204372 0.46023842 0.67792545 0.52115943 0.4490534 ]


### compute the standard deviation & variance

In [67]:
# compute the overall standard deviation
print(np.std(arr))

0.25305273176784365


In [68]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.15100481 0.26938074 0.18260514 0.20008424 0.33508033]


In [69]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.33997649 0.21759869 0.29739013 0.20049061 0.13310804]


In [70]:
# compute the overall variance
print(np.var(arr))

0.06403568505516823


In [71]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.02280245 0.07256599 0.03334464 0.0400337  0.11227883]


In [72]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.11558401 0.04734919 0.08844089 0.04019649 0.01771775]


### compute cumulative sum & product

In [73]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[0.87350227 0.02942373 0.55204372 0.2402475  0.88480501]
 [1.33374069 0.22259406 0.84573623 1.05817501 1.44429239]
 [2.01166614 1.03172074 1.71430838 1.47616747 1.50323054]
 [2.49012514 1.55288017 2.2949404  1.78536647 2.42311317]
 [3.14547265 1.90212156 2.83603444 2.23441986 2.70543413]]


In [74]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.87350227 0.902926   1.45496972 1.69521723 2.58002224]
 [0.46023842 0.65340875 0.94710126 1.76502877 2.32451614]
 [0.67792545 1.48705213 2.35562428 2.77361674 2.83255489]
 [0.478459   0.99961843 1.58025045 1.88944945 2.80933208]
 [0.6553475  1.00458889 1.54568293 1.99473633 2.27705729]]


In [75]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[8.73502266e-01 2.94237336e-02 5.52043722e-01 2.40247504e-01
  8.84805011e-01]
 [4.02019307e-01 5.68379233e-03 1.62131103e-01 1.96505042e-01
  4.95037234e-01]
 [2.72539118e-01 4.59890800e-03 1.40822561e-01 8.21376253e-02
  2.91765815e-02]
 [1.30398795e-01 2.39676427e-03 8.17660882e-02 2.53968714e-02
  2.68390304e-02]
 [8.54565249e-02 8.37049274e-04 4.42431433e-02 1.14045514e-02
  7.57722084e-03]]


In [76]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[0.87350227 0.0257017  0.01418846 0.00340874 0.00301607]
 [0.46023842 0.08890441 0.02611056 0.02135654 0.01194872]
 [0.67792545 0.54852757 0.47643577 0.19914656 0.01173733]
 [0.478459   0.24935342 0.14478258 0.04476663 0.04118004]
 [0.6553475  0.22887447 0.12384261 0.05561195 0.01570042]]


### element-wise comparison

In [77]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [78]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


# 6. Slicing & Indexing

In [79]:
arr = np.array(range(100)).reshape((10,10))

### select an element by row and column indices

In [80]:
print(arr[5][5])
# or 
print(arr[5,5])

55
55


### indexing with slicing

In [81]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [82]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])    

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### assign a scalar to a slice by broadcasting

In [83]:
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


### boolean indexing

In [84]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [85]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [86]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])    

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [87]:
arr = np.random.rand(10,10)

In [88]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[0.05662    0.50942926 0.19017372]


In [89]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[0.44064297 0.15703523 0.20587172]
 [0.80738444 0.25584293 0.68618686]
 [0.0480298  0.40335482 0.26591121]]


### dimension inference

In [90]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


# 7. Sort Arrays

In [91]:
arr = np.random.rand(5,5)

### sort an array along a specified axis

In [92]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.18181153 0.11720684 0.33997017 0.30511365 0.07722273]
 [0.40939041 0.24816989 0.47933417 0.31354249 0.09966921]
 [0.55382711 0.37251939 0.60434016 0.43458619 0.52820553]
 [0.58201533 0.52101088 0.68361547 0.81257008 0.89730494]
 [0.59655266 0.71249243 0.78460482 0.9466209  0.91323126]]


In [93]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.18181153 0.11720684 0.33997017 0.30511365 0.07722273]
 [0.40939041 0.24816989 0.47933417 0.31354249 0.09966921]
 [0.55382711 0.37251939 0.60434016 0.43458619 0.52820553]
 [0.58201533 0.52101088 0.68361547 0.81257008 0.89730494]
 [0.59655266 0.71249243 0.78460482 0.9466209  0.91323126]]


In [94]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.07722273 0.11720684 0.18181153 0.30511365 0.33997017]
 [0.09966921 0.24816989 0.31354249 0.40939041 0.47933417]
 [0.37251939 0.43458619 0.52820553 0.55382711 0.60434016]
 [0.52101088 0.58201533 0.68361547 0.81257008 0.89730494]
 [0.59655266 0.71249243 0.78460482 0.91323126 0.9466209 ]]


In [95]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.07722273 0.11720684 0.18181153 0.30511365 0.33997017]
 [0.09966921 0.24816989 0.31354249 0.40939041 0.47933417]
 [0.37251939 0.43458619 0.52820553 0.55382711 0.60434016]
 [0.52101088 0.58201533 0.68361547 0.81257008 0.89730494]
 [0.59655266 0.71249243 0.78460482 0.91323126 0.9466209 ]]


# 8. Copy Arrays

In [96]:
arr = np.array([1,2,3])

In [97]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

# 9. Manipulate Arrays

In [98]:
arr = np.random.rand(3,4)

### transpose an array

In [99]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.05125491 0.57513529 0.62972763]
 [0.38031548 0.32256775 0.40101228]
 [0.56385654 0.98392756 0.74463006]
 [0.13257374 0.57566582 0.40118593]]
[[0.05125491 0.57513529 0.62972763]
 [0.38031548 0.32256775 0.40101228]
 [0.56385654 0.98392756 0.74463006]
 [0.13257374 0.57566582 0.40118593]]
[[0.05125491 0.57513529 0.62972763]
 [0.38031548 0.32256775 0.40101228]
 [0.56385654 0.98392756 0.74463006]
 [0.13257374 0.57566582 0.40118593]]


### transpose of a high dimensional array with specified order of axes

In [100]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### swap axes

In [101]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [102]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.05125491, 0.38031548, 0.56385654, 0.13257374, 0.57513529,
        0.32256775],
       [0.98392756, 0.57566582, 0.62972763, 0.40101228, 0.74463006,
        0.40118593]])

In [103]:
# change the shape of an array in place
arr.resize((2,6))

### flatten an array

In [104]:
# return a copy
arr.flatten()    

array([0.05125491, 0.38031548, 0.56385654, 0.13257374, 0.57513529,
       0.32256775, 0.98392756, 0.57566582, 0.62972763, 0.40101228,
       0.74463006, 0.40118593])

In [105]:
# return a view
# change any element in the view will also change the initial array
arr.ravel()      

array([0.05125491, 0.38031548, 0.56385654, 0.13257374, 0.57513529,
       0.32256775, 0.98392756, 0.57566582, 0.62972763, 0.40101228,
       0.74463006, 0.40118593])

### append elements to an array

In [106]:
arr = np.array([1,2,3])

In [107]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [108]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [109]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [110]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


### delete elements from an array

In [111]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [112]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


# 10. Combine & Split Arrays

In [113]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### np.concatenate((a, b), axis=0)

In [114]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [115]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### np.vstack((a, b)) 
### np.r_[a, b]

In [116]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [117]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### np.hstack((a, b))
### np.c_[a, b]

In [118]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [119]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split the array 

In [120]:
arr = np.random.rand(6,6)

In [121]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.76547512, 0.98243124, 0.16811677, 0.47459468, 0.54894048,
        0.43610734],
       [0.2967313 , 0.39356374, 0.83808113, 0.65164256, 0.95389693,
        0.47700023],
       [0.87889355, 0.79220778, 0.26535752, 0.76243827, 0.8227364 ,
        0.35299237]]), array([[0.97423198, 0.67523336, 0.69937965, 0.45959692, 0.06973492,
        0.99798018],
       [0.63775096, 0.06815258, 0.14613704, 0.83891327, 0.27719491,
        0.53945097],
       [0.08043277, 0.56634674, 0.36248491, 0.31821364, 0.65352326,
        0.354903  ]])]


In [122]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.76547512, 0.98243124, 0.16811677],
       [0.2967313 , 0.39356374, 0.83808113],
       [0.87889355, 0.79220778, 0.26535752],
       [0.97423198, 0.67523336, 0.69937965],
       [0.63775096, 0.06815258, 0.14613704],
       [0.08043277, 0.56634674, 0.36248491]]), array([[0.47459468, 0.54894048, 0.43610734],
       [0.65164256, 0.95389693, 0.47700023],
       [0.76243827, 0.8227364 , 0.35299237],
       [0.45959692, 0.06973492, 0.99798018],
       [0.83891327, 0.27719491, 0.53945097],
       [0.31821364, 0.65352326, 0.354903  ]])]


# 11. Set Operations

### select the unique elements from an array

In [123]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


### compute the intersection & union of two arrays

In [124]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [125]:
# intersection
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [126]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


### compute whether each element of an array is contained in another

In [127]:
print(np.in1d(arr1, arr2))

[False False  True  True  True]


### compute elements in an array that are not in another

In [128]:
print(np.setdiff1d(arr1, arr2))

[1 2]


### compute elements in either of two arrays, but not both

In [129]:
print(np.setxor1d(arr1, arr2))

[1 2 6 7]


# 12. Linear Algebra

In [130]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

### matrix multiplication

In [131]:
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[1.27031576 2.10936766 1.11272394 1.53442392 1.32212589]
 [0.60803251 0.83430863 0.49963791 0.72929852 0.87059865]
 [1.71578965 2.33895573 1.34703992 1.9650433  1.30320173]
 [1.48765144 2.34737938 1.52953325 1.72727539 1.27152512]
 [1.4099209  1.81270088 1.05526591 1.75085306 1.1438742 ]]
[[1.27031576 2.10936766 1.11272394 1.53442392 1.32212589]
 [0.60803251 0.83430863 0.49963791 0.72929852 0.87059865]
 [1.71578965 2.33895573 1.34703992 1.9650433  1.30320173]
 [1.48765144 2.34737938 1.52953325 1.72727539 1.27152512]
 [1.4099209  1.81270088 1.05526591 1.75085306 1.1438742 ]]
[[1.27031576 2.10936766 1.11272394 1.53442392 1.32212589]
 [0.60803251 0.83430863 0.49963791 0.72929852 0.87059865]
 [1.71578965 2.33895573 1.34703992 1.9650433  1.30320173]
 [1.48765144 2.34737938 1.52953325 1.72727539 1.27152512]
 [1.4099209  1.81270088 1.05526591 1.75085306 1.1438742 ]]


### QR factorization 

In [132]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-0.41438112  0.07291901 -0.27039749 -0.09908947 -0.86025437]
 [-0.42241766 -0.12362345  0.17012864 -0.8491238   0.23733012]
 [-0.44856711  0.29628117 -0.69914817  0.16350579  0.44211165]
 [-0.08528906  0.90097679  0.42505603 -0.00784183 -0.01524727]
 [-0.66435301 -0.28259221  0.47797558  0.49231537  0.0891159 ]]
[[-1.30790082 -1.32305402 -0.23131722 -1.10121838 -1.02086159]
 [ 0.          0.43615131  0.38245894  0.38209129  0.23379438]
 [ 0.          0.          0.18978558 -0.60729373  0.26969486]
 [ 0.          0.          0.         -0.31324721 -0.31737632]
 [ 0.          0.          0.          0.         -0.37402655]]


### singular value decomposition (SVD)

In [133]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.47460836 -0.11848832 -0.16863875  0.43247357  0.7384003 ]
 [-0.27287472 -0.38832842  0.43478107 -0.71265199  0.27898564]
 [-0.46617571  0.28256245  0.70745281  0.34153178 -0.29275455]
 [-0.50883197  0.62330595 -0.40994246 -0.42337042 -0.07269377]
 [-0.47334609 -0.60564817 -0.33761531  0.09595457 -0.53473582]]
[2.13458064 0.96316343 0.68944953 0.22929005 0.12216484]
[[-0.43274573 -0.36619504 -0.51291968 -0.5113381  -0.39252908]
 [ 0.11006995 -0.0593174   0.72746102 -0.32766152 -0.58974948]
 [-0.64364542 -0.11431637  0.16366426  0.68148701 -0.28538012]
 [ 0.05867433  0.80912057 -0.31283238  0.06099473 -0.49020075]
 [ 0.61878399 -0.44117833 -0.28820788  0.40376525 -0.41997368]]


### compute eigen values

In [134]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.72562923 -0.78854214 -0.12797539  0.66475412  0.31238337]


### eigen value decomposition

In [135]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.22816712+0.j          0.75805151+0.1003946j   0.75805151-0.1003946j
 -0.25553092+0.30799163j -0.25553092-0.30799163j]
[[-0.20467304+0.j          0.1171861 -0.43405946j  0.1171861 +0.43405946j
   0.25256126+0.03169577j  0.25256126-0.03169577j]
 [-0.64370689+0.j         -0.26558548+0.32572768j -0.26558548-0.32572768j
   0.36025193+0.37358557j  0.36025193-0.37358557j]
 [-0.35239901+0.j          0.13237621-0.08365415j  0.13237621+0.08365415j
  -0.5511151 +0.j         -0.5511151 -0.j        ]
 [-0.55405758+0.j          0.62029413+0.j          0.62029413-0.j
   0.38360252+0.08823937j  0.38360252-0.08823937j]
 [-0.33553766+0.j         -0.39323808+0.23938078j -0.39323808-0.23938078j
  -0.27380276-0.36363122j -0.27380276+0.36363122j]]


### compute the trace & determinant

In [136]:
# notice this is not a function in linalg!!!
print(np.trace(arr))    

3.233208302355474


In [137]:
print(np.linalg.det(arr))

0.20865884162683893


### calculate the inverse/psedo-inverse of a matrix

In [138]:
arr = np.random.rand(5,5)

In [139]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[-0.17331986  1.55682968  0.40103671 -0.63274064 -0.41314542]
 [ 0.34644083 -0.19830023 -0.47679801 -0.11163135  1.45823837]
 [-0.56284749 -1.55144295  0.61696684  0.62545543  1.30107159]
 [-0.81238533  0.06826413 -1.20341171  1.7724115  -0.35892702]
 [ 2.1585909   0.84254772  1.13378708 -1.43821118 -2.63573492]]


In [140]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[-0.17331986  1.55682968  0.40103671 -0.63274064 -0.41314542]
 [ 0.34644083 -0.19830023 -0.47679801 -0.11163135  1.45823837]
 [-0.56284749 -1.55144295  0.61696684  0.62545543  1.30107159]
 [-0.81238533  0.06826413 -1.20341171  1.7724115  -0.35892702]
 [ 2.1585909   0.84254772  1.13378708 -1.43821118 -2.63573492]]


### solve a linear system

In [141]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

[ -0.45324003   5.36411281   7.19234684   1.00891872 -11.68647173]


In [142]:
# calculate the least-squares solution of a linear system
y = [1,2,3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print(residuals)
print(rank)
print(singular)

[ -0.45324003   5.36411281   7.19234684   1.00891872 -11.68647173]
[]
5
[2.59787731 0.85950491 0.57695417 0.4184869  0.21448546]


C:\Users\ewang\AppData\Local\Continuum\miniconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until
